LoadingBar.cs

Loading Bar, 0-100, kleur is veranderbaar.

Loading Bar

---

LoadingBar.cs

Kleur veranderd, methode naam veranderd.

Changed loading bar color

---

DisplayMovie.cs
MovieSchedule.cs
Program.cs

Used indexing for selecting options, caused problems with the left arrow key input which returns Count => lead to index error

Fixed the back option in movie schedule

---

Auditorium1.cs
logIn.cs

Changed Main to Start, commented out loading bar

---

TheaterHandler.cs

Length of movie screen gets adjusted to the length of the seating overview

Fixed movie screen display

---

DisplayMovie.cs

Testing User DISCORD

---

DisplayMovie.cs

RESTORE OFFICIAL

---

LoginHandler.cs
PasswordValidator.cs
Program.cs
User.cs

Inog Aangemaakt, password checker aangemaakt.

Triwan's inlog

---

AdminHandler.cs
LoginHandler.cs
Menu.cs
Program.cs

Changed how the login and registration is displayed to the user.

Login reformatting

---

AdminHandler.cs
LoginHandler.cs
Program.cs
ShowHandler.cs

- Correct header is now displayed to the admin when adding shows to the schedule
- Shows are now ordered by time when displayed to the user
- Minor changes to display during user registration
- Fixed the exit option for the user, now goes back to standby
- Fixed the exit option of the admin, now leaves the menu and goes back to standby

Fix-and-Changes/Minor-changes

---

LoginHandler.cs
Program.cs

Login And Register in the program.cs modified for booleons

Login And Register in the program.cs modified for booleons

---

AdminHandler.cs
LoginHandler.cs
Program.cs
User.cs

Finalized Admin inlog, cleaned the code and tested the app

Triwan's admin

---

AdminHandler.cs

TO DO:
- fix having to restart application to bypass "no movies" message
- add remove movie functionality

Added functionality to add movies

---

LoginHandler.cs

Restored Main

---

ShipsCinema/Program.cs
ShipsCinema/ReservationHandler.cs

- GetReservationsByUser:
This method has been updated.
Now u can see a menu with the movies the user has reservations for.
U select the movie 
- This will be implimented before the end of this week. (24-11-2023):
I will impliment that the user will get to see the different reservation codes with how many seats it has.
When the user clicks on it you will be able to see the chair position of how many reservations they have on that one                      
code / group.

ReservationHandler.cs method created, and updated into program.cs

---

ShipsCinema/MovieHandler.cs
ShipsCinema/ShowHandler.cs

- user now goes back to selection screen of movie details/showings
- Reordered previous/next page and back

Small changes

---

ShipsCinema/Handlers/ShowHandler.cs

Changed to: Datasources/shows.json

Corrected filepath in ShowHandler

---

ShipsCinema/Datasources/tickets.json
ShipsCinema/Handlers/CheckOutHandler.cs
ShipsCinema/Handlers/ReservationHandler.cs
ShipsCinema/Handlers/TheaterHandler.cs
ShipsCinema/Presentation/Program.cs

Checkout moved in the selectseats in theatherhandler.

Fixed errors with reservations and check-out

---

ShipsCinema/Handlers/ShowHandler.cs

- Movie now only appears in movie list if it is scheduled for future showings
- Outdated showings now don't appear in showing overview for a movie

Dont display outdated showings

---

ShipsCinema/Datamodels/Seat.cs
ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/CheckOutHandler.cs
ShipsCinema/Logic/ReservationHandler.cs
ShipsCinema/Logic/TheaterHandler.cs
ShipsCinema/Presentation/Program.cs

PULL REQUEST ATTEMPT NO. 2
Reservation is no longer made when the user quits out of the application during checkout.

ATTEMPT NO. 2: Fixed Reservations bug

---

ShipsCinema/Datamodels/Seat.cs
ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/CheckOutHandler.cs
ShipsCinema/Logic/MovieHandler.cs
ShipsCinema/Logic/ReservationHandler.cs
ShipsCinema/Logic/ShowHandler.cs
ShipsCinema/Logic/TheaterHandler.cs
ShipsCinema/Presentation/Program.cs

ATTEMPT NO. 2: Fix/admin seats unavailable

---

ShipsCinema/Presentation/ChangeMovieDetails.cs

- Admin can no longer change movie id through the program
- Current movie data now visible when scrolling through the edit movie menu

View data when editing movie details

---

ShipsCinema/Logic/ShowHandler.cs

Dates in admin menu now sorted in descending order

changed date order

---

ShipsCinema/Datamodels/User.cs
ShipsCinema/Datasources/UserAccounts.json
ShipsCinema/Datasources/movies.json
ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/CheckOutHandler.cs
ShipsCinema/Logic/Menu.cs
ShipsCinema/Logic/MovieHandler.cs
ShipsCinema/Logic/ShowHandler.cs
ShipsCinema/Logic/UserAccountsHandler.cs
ShipsCinema/Presentation/ChangeMovieDetails.cs

Meant to have functionality to change admin rights in a separate branch, my bad.
Changes
- User can use the left and right arrow keys to navigate through the pages.
- Page numbers are displayed next to the "Previous Page" option.
- The Main Admin can give other users admin rights (new file to allow this: UserAccountsHandler.cs)
- Changed the default user account in UserAccounts.json
- Added indentation to movies.json and removed the 'Kaas' movie.
- Several changes to presentation to make the app more consistent.

Admin showing schedule pagination 2

---

ShipsCinema/Datamodels/User.cs
ShipsCinema/Datasources/UserAccounts.json
ShipsCinema/Datasources/movies.json
ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/CheckOutHandler.cs
ShipsCinema/Logic/Menu.cs
ShipsCinema/Logic/MovieHandler.cs
ShipsCinema/Logic/ShowHandler.cs
ShipsCinema/Logic/UserAccountsHandler.cs
ShipsCinema/Presentation/ChangeMovieDetails.cs

* Added arrow key navigation and page numbers
* Added functionality to change admin rights
* Refactored code
List of users now gets ordered based on Admin rights, then by Id
* Refactored code to separate Logic and Presentation
* Added an extra check when changing rights
Added an extra check to ensure Main Admin rights will never get changed.
* Minor changed to check for admin rights
* Write the changes to the json
* Display changes
* Minor changes
* Minor presentation changes
* Changed admin rights functionality
Only the Main Admin is allowed to change admin rights
* Removed kaas
* Changed the default user account

Admin showing schedule pagination 2 (#156)

---

ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/CheckOutHandler.cs
ShipsCinema/Logic/Menu.cs
ShipsCinema/Logic/MovieHandler.cs
ShipsCinema/Logic/ReservationHandler.cs
ShipsCinema/Logic/ShowHandler.cs
ShipsCinema/Presentation/ChangeMovieDetails.cs
ShipsCinema/Presentation/Program.cs

Implemented functionality where the user can go from the current movies and the overview of showtimes to seat selection.

User can go from current movies to seat selection

---

ShipsCinema/Datamodels/HasID.cs
ShipsCinema/Datamodels/Movie.cs
ShipsCinema/Datamodels/Show.cs
ShipsCinema/Datamodels/User.cs
ShipsCinema/Logic/AdminHandler.cs
ShipsCinema/Logic/ShowHandler.cs
ShipsCinemaTest/Unit Tests/LogInHandlerTest.cs

- Voorheen werd de vraag om bevestig herhaalt bij een andere toets dan "Y" of "N" wanneer de admin een showing probeert te verwijderen.
- In het admin panel toegevoegd dat "view" ook mogelijk is bij de optie "showings" voor duidelijkheid.
- Interface HasID toegevoegd en geimplementeerd.

added interface and minor changes 
